services:
  - type: web
    name: projet-nlp-api
    env: python
    runtime: python-3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
